[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util", package = "crust-util" }
common = { path = "../common", package = "crust-common" }

serde_json = "1.0.82"

